tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "buo/cask-upgrade"
tap "hashicorp/tap"

# CLI Tools
brew "mas" # Mac App Store command-line interface
brew "gh" # GitHub CLI
brew "glab" # GitLab CLI
brew "git-delta" # Git diff viewer
brew "git-lfs" # Git Large File Storage
brew "coreutils" # GNU Core Utilities
brew "gnu-tar" # GNU tar
brew "ack" # grep-like tool optimized for programmers
brew "bat" # Enhanced cat with syntax highlighting
brew "jq" # JSON processor
brew "zsh-autosuggestions" # Zsh autosuggestions
brew "pre-commit" # Pre-commit hooks manager
brew "tree" # Directory tree viewer
brew "graphviz" # Graph visualization software

# Development Tools
brew "tmux" # Terminal multiplexer
brew "gnupg" # PGP encryption
brew "awscli" # AWS command-line tools
brew "aliyun-cli" # Alibaba Cloud CLI
cask "google-cloud-sdk"
brew "imagemagick" # Image processing
brew "terraformer" # Infrastructure as Code tool
brew "terragrunt" # Terraform wrapper
brew "packer" # Machine image builder
brew "ansible" # IT automation
brew "hashicorp/tap/terraform" # Terraform
brew "infracost" # Cloud cost estimation
brew "asdf" # Version manager
brew "tesseract" # OCR engine
brew "mackup" # Keep your application settings in sync

# Python
brew "python"

# PHP
brew "composer"

# Development Applications
cask "visual-studio-code"
cask "paw"
cask "docker"
cask "warp"
cask "multipass" # Ubuntu VM manager

# Applications
cask "1password"
cask "1password-cli"
cask "appcleaner"
cask "notion"
cask "whatsapp"
cask "google-chrome"
cask "discord"
cask "telegram-desktop"
cask "the-unarchiver"

# Fonts
cask "font-fira-code"
cask "font-lato"
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-abel"
cask "font-fjalla-one"
cask "font-inter"
cask "font-sf-mono"
cask "font-signika"

# Mac App Store Apps
mas "LINE", id: 539883307
mas "Tomato One", id: 907364780
