# tap "homebrew/bundle"
# tap "homebrew/cask-versions"
# tap "homebrew/cask-fonts"
# tap "homebrew/services"
tap "buo/cask-upgrade"
tap "hashicorp/tap"

# CLI Tools
brew "mas" # Mac App Store command-line interface
brew "gh" # GitHub CLI
brew "glab" # GitLab CLI
brew "git-delta" # Git diff viewer
brew "git-lfs" # Git Large File Storage
brew "coreutils" # GNU Core Utilities
brew "gnu-tar" # GNU tar
brew "ack" # grep-like tool optimized for programmers
brew "bat" # Enhanced cat with syntax highlighting
brew "jq" # JSON processor
brew "zsh-autosuggestions" # Zsh autosuggestions
brew "pre-commit" # Pre-commit hooks manager
brew "tree" # Directory tree viewer
brew "graphviz" # Graph visualization software

# Development Tools
brew "tmux" # Terminal multiplexer
brew "gnupg" # PGP encryption
brew "awscli" # AWS command-line tools
brew "aliyun-cli" # Alibaba Cloud CLI
cask "google-cloud-sdk"
brew "imagemagick" # Image processing
# brew "terraformer" # Infrastructure as Code tool (deprecated) 由 tenv 替代
# brew "terragrunt" # Terraform wrapper (deprecated) 由 tenv 替代
# brew "packer" # Machine image builder (deprecated) 由 tenv 替代
brew "ansible" # IT automation
brew "hashicorp/tap/terraform" # Terraform
brew "infracost" # Cloud cost estimation
brew "asdf" # Version manager
brew "tesseract" # OCR engine
brew "mackup" # Keep your application settings in sync
brew "cookiecutter" # Create projects from project templates

# Python
brew "python"

# PHP
brew "composer"

# JS
brew "volta" # 取代 nvm

# DevOps
brew "fluent-bit"
brew "minikube"

# Development Applications
cask "charles" # HTTP 请求调试工具
cask "drawio" # 图形工具
cask "visual-studio-code"
cask "docker"
cask "warp"
cask "multipass" # Ubuntu VM manager
cask "dbngin"
cask "herd"
cask "rapidapi"
cask "jetbrains-toolbox"

# Applications
cask "1password"
cask "1password-cli"
cask "appcleaner"
cask "notion"
cask "whatsapp"
cask "google-chrome"
cask "discord"
cask "telegram-desktop"
cask "the-unarchiver"
cask "gather"
cask "arc"

# Fonts
cask "font-fira-code"
cask "font-lato"
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-abel"
cask "font-fjalla-one"
cask "font-inter"
cask "font-sf-mono"
cask "font-signika"

# Mac App Store Apps
mas "LINE", id: 539883307
mas "Tomato One", id: 907364780
